name: 'close-stale-repos'
description: 'Identify stale repositories and report them'
author: 'Alexander Lanin'

inputs:
  organization:
    description: 'Which organization to check; defaults to the current organization'
    default: ${{ github.repository_owner }}
    required: true

  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
